Comenzamos la evaluación del finetuning mediante Ragas cargando las librerías pertinentes, que nos dieron bastantes problemas, solucionados finalmente por Claude, porque Gemini se vio superado.

In [ ]:
!pip install --upgrade pip -q
!pip install ragas langchain-community langchain-openai pandas datasets langchain-google-vertexai -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 8.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [ ]:
# 1. Instalación de Unsloth ligero y dependencias de inferencia
!pip install --no-deps "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers peft accelerate bitsandbytes

Collecting unsloth @ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-7mbw3hfk/unsloth_f749d26e32724622b39bc16aa64c2fd3
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-7mbw3hfk/unsloth_f749d26e32724622b39bc16aa64c2fd3
  Resolved https://github.com/unslothai/unsloth.git to commit 37d3b6fdf7d3b18684a88f13c463a6db22e6e2ce
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: unsloth
  Building wheel for unsloth (pyproject.toml) ... done
  Created wheel for unsloth: filename=unsloth-2026.8.22-py3-none-any.whl size=45113769 sha256=af07a5219e1b75f5c21d94f775a1b15803e6b1becf47bf160da9d6e3f194bb9a
  Stored in directory: /tmp/pip-ephem-wheel-cache-v17r_ce_/wheels/d5/36/1d/4e65996c5b80c84a5ac1b0ba10718bdc155f8dd04352746a8f
Successfully built unsloth
Installing collected packages: unsloth
Successfully installed unsloth-2026.8.22
Collecting xformers
  Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.13/dist-packages (0.20.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.13/dist-packages (1.14.0)
Collecting bitsandbytes
  Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 51.2 MB/s  0:00:00
Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl (43.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 58.8 MB/s  0:00:00
Installing collected packages: xformers, bitsandbytes
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [bitsandbytes]
Successfully installed bitsandbytes-0.50.2 xformers-0.0.35

In [ ]:
pip install unsloth_zoo

Collecting unsloth_zoo
  Downloading unsloth_zoo-2026.8.16-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: torch<2.13.0,>=2.4.0 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (2.11.0+cu128)
Collecting torchao>=0.13.0 (from unsloth_zoo)
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (3.6.0)
Collecting tyro (from unsloth_zoo)
  Downloading tyro-1.0.16-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (1.14.0)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth_zoo)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (0.20.0)
Collecting cut_cross_entropy (from unsloth_zoo)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (26.3)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth_zoo)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth_zoo)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (0.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (0.48.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (2.1.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (5.29.6)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (1.28.0)
Collecting hf_transfer (from unsloth_zoo)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (11.3.0)
Requirement already satisfied: regex in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (2025.11.3)
Collecting msgspec (from unsloth_zoo)
  Downloading msgspec-0.21.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (4.16.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo) (3.32.4)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (4.0.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0->unsloth_zoo) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0->unsloth_zoo) (1.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth_zoo) (3.4.5)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth_zoo) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch<2.13.0,>=2.4.0->unsloth_zoo) (1.7.0)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (0.27.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (0.8.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (1.24.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch<2.13.0,>=2.4.0->unsloth_zoo) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch<2.13.0,>=2.4.0->unsloth_zoo) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth_zoo) (0.1.2)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.13/dist-packages (from tyro->unsloth_zoo) (0.18.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from tyro->unsloth_zoo) (4.6.0)
Downloading unsloth_zoo-2026.8.16-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 18.8 MB/s  0:00:00
Downloading datasets-4.3.0-py3-none-any.whl (506 kB)
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 60.2 MB/s  0:00:00
Downloading trl-0.24.0-py3-none-any.whl (423 kB)
Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 120.9 MB/s  0:00:00
Downloading cut_cross_entropy-25.1.1-py3-none-any.whl (22 kB)
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 92.0 MB/s  0:00:00
Downloading msgspec-0.21.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (225 kB)
Downloading tyro-1.0.16-py3-none-any.whl (216 kB)
Installing collected packages: torchao, msgspec, hf_transfer, tyro, datasets, transformers, cut_cross_entropy, trl, unsloth_zoo
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.15.1
    Uninstalling transformers-5.15.1:
      Successfully uninstalled transformers-5.15.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [unsloth_zoo]
Successfully installed cut_cross_entropy-25.1.1 datasets-4.3.0 hf_transfer-0.1.9 msgspec-0.21.1 torchao-0.18.0 transformers-5.5.0 trl-0.24.0 tyro-1.0.16 unsloth_zoo-2026.8.16

La librería más problemática fue llama-cpp-python que cargamos inicialmente de forma simple, como recomienda HF, pero que Claude rectificó, con el código de la celda siguiente.

In [ ]:
!pip install -U llama-cpp-python

Collecting llama-cpp-python
  Using cached llama_cpp_python-0.3.35-py3-none-linux_x86_64.whl
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from llama-cpp-python) (4.16.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from llama-cpp-python) (2.1.3)
Requirement already satisfied: diskcache>=5.6.1 in /usr/local/lib/python3.13/dist-packages (from llama-cpp-python) (5.6.3)
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.13/dist-packages (from llama-cpp-python) (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2>=2.11.3->llama-cpp-python) (3.0.3)
Installing collected packages: llama-cpp-python
Successfully installed llama-cpp-python-0.3.35

In [ ]:
# Cell de instalación: sustituye la celda 5 por esto
!pip uninstall -y llama-cpp-python

# Wheel precompilada para CUDA 12.x (Colab T4)
!pip install llama-cpp-python \
  --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu122 \
  --no-cache-dir -q

Found existing installation: llama_cpp_python 0.3.35
Uninstalling llama_cpp_python-0.3.35:
  Successfully uninstalled llama_cpp_python-0.3.35

Tuvimos problemas porque el modelo no se cargaba en la GPU, sino en la RAM del sistema, lo que dificultaba la inferencia del modelo Gemma 3. La celda siguiente mostraba que la GPU estaba disponible.

In [ ]:
# Celda de diagnóstico - ejecutar ANTES de cargar el modelo
import subprocess
result = subprocess.run(['nvidia-smi'], capture_output=True, text=True)
print(result.stdout)

from llama_cpp import Llama
import llama_cpp
print(f"llama-cpp-python version: {llama_cpp.__version__}")

# Verificar que la build tiene soporte CUDA
print(f"CUDA disponible según llama_cpp: {llama_cpp.llama_supports_gpu_offload()}")

Fri Aug 28 08:40:15 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

ggml_cuda_init: found 1 CUDA devices (Total VRAM: 14912 MiB):
  Device 0: Tesla T4, compute capability 7.5, VMM: yes, VRAM: 14912 MiB

llama-cpp-python version: 0.3.35
CUDA disponible según llama_cpp: True

Cargamos las librerías de OpenAI, y especialmente las métricas de Ragas, que utilizaremos después.

In [ ]:
import sys
import types

# 1. Parche en memoria para evitar el conflicto con langchain_community / VertexAI
dummy_module = types.ModuleType("langchain_community.chat_models.vertexai")
dummy_module.ChatVertexAI = type("ChatVertexAI", (object,), {})
sys.modules["langchain_community.chat_models.vertexai"] = dummy_module

import os
import pandas as pd
from datasets import Dataset

# Librerías de LangChain
from langchain_openai import ChatOpenAI
from langchain_community.embeddings import HuggingFaceEmbeddings

# 2. Imports actualizados de Ragas (usando 'ragas.metrics.collections')
from ragas import evaluate
from ragas.metrics.collections import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)


print("✅ Todos los módulos e imports se han cargado sin ningún warning.")

/tmp/ipykernel_48715/1819823276.py:15: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.embeddings import HuggingFaceEmbeddings

✅ Todos los módulos e imports se han cargado sin ningún warning.

Cargamos preliminarmente la clave de DeepSeek, en la celda siguiente codificamos el judge. Repetiremos el proceso más adelante, dentro de la celda donde ejecutamos Ragas.

In [ ]:
from google.colab import userdata
DEEPSEEK_API_KEY = userdata.get('DEEPSEEK_API_KEY')

In [ ]:
# os.environ["OPENAI_API_KEY"] = "TU_API_KEY_AQUI"
DEEPSEEK_BASE_URL = "https://openrouter.ai/api/v1" # Ajusta si usas otro proveedor

# 2. Inicializar el Judge con DeepSeek V4 Pro
deepseek_judge = ChatOpenAI(
    model="deepseek/deepseek-v4-pro", # Ajusta el identificador según tu proveedor (ej. deepseek-ai/DeepSeek-V4-Pro)
    openai_api_key=DEEPSEEK_API_KEY,
    openai_api_base=DEEPSEEK_BASE_URL,
    temperature=0.0 # Se recomienda 0 para evaluación consistente
)

# 3. Embeddings (Ragas usa embeddings para calcular métricas como answer_relevance)
# Puedes usar un modelo de HuggingFace ligero o el de OpenAI/proveedor
from langchain_community.embeddings import HuggingFaceEmbeddings
eval_embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

/tmp/ipykernel_48715/3952755969.py:15: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  eval_embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Ahora tenemos que configurar el diccionario que pasaremos a Ragas, cargando el fichero de test con los ejemplos en formato .jsonl. Pasamos estos a un dataframe de Pandas, y de ahí al diccionario con el formato Ragas, a falta de las respuestas del modelo Gemma3.

In [ ]:
import pandas as pd
from datasets import Dataset

In [ ]:
# Carga de los ejemplos de text, con lo que probaremos el modelo
import pandas as pd
df_eval = pd.read_json('/content/drive/MyDrive/Ollama_app_comentario/test/dataset_market_commentary_test.jsonl', lines=True) # OJO!!

In [ ]:
# Preparación de los datos para introducirlos en el diccionario requerido por Ragas

df_eval['instructions'] = df_eval['messages'].apply(lambda x: x[0]['content'])
df_eval['contexts'] = df_eval['messages'].apply(lambda x: x[1]['content'])
df_eval['ground_truth'] = df_eval['messages'].apply(lambda x: x[2]['content'])
df_eval['question'] = df_eval['instructions'] + '\n\n' + df_eval['contexts']

question = df_eval['question'].tolist()
ground_truth = df_eval['ground_truth'].tolist()
contexts = [[item] for item in df_eval['contexts'].tolist()]

In [ ]:
# Relleno de campos necesarios del diccionario data, requerido por Ragas

data = {}
data['question'] = question
data['contexts'] = contexts
data['ground_truth'] = ground_truth

Cargamos torch y librerías de unsloth para poder descargar el modelo Gemma 3 en local.

In [ ]:
from unsloth import FastLanguageModel
import torch

/usr/local/lib/python3.13/dist-packages/unsloth/__init__.py:1531: UserWarning: WARNING: Unsloth should be imported before [transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from ._gpu_init import *

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

Descargamos el modelo de Gemma3 desde Hugging Face.

In [ ]:
from huggingface_hub import hf_hub_download
from llama_cpp import Llama

# 1. Descargar únicamente el archivo .gguf
model_path = hf_hub_download(
    repo_id="GuillermoBarrio/gemma3-4b-finetuned-comentarios-gguf",
    filename="gemma-3-4b-it.Q4_K_M.gguf"
)

# 2. Cargar modelo en GPU

model = Llama(
    model_path=model_path,
    n_ctx=6000,
    n_gpu_layers=99,
    n_batch=512,
    flash_attn=True,
    verbose=True   # ← cámbialo a True temporalmente
)


print("✅ Modelo cargado con éxito en VRAM")

llama_model_loader: loaded meta data with 39 key-value pairs and 444 tensors from /root/.cache/huggingface/hub/models--GuillermoBarrio--gemma3-4b-finetuned-comentarios-gguf/snapshots/3ef2f2ff5b5311b762bea45fddbe7f0eaf4095bf/gemma-3-4b-it.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma3
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                     general.sampling.top_k i32              = 64
llama_model_loader: - kv   3:                     general.sampling.top_p f32              = 0.950000
llama_model_loader: - kv   4:                               general.name str              = Unsloth_Gguf_Giis7Gso
llama_model_loader: - kv   5:                       general.quantized_by str              = Unsloth
llama_model_loader: - kv   6:                         general.size_label str              = 3.9B
llama_model_loader: - kv   7:                           general.repo_url str              = https://huggingface.co/unsloth
llama_model_loader: - kv   8:                               general.tags arr[str,2]       = ["unsloth", "llama.cpp"]
llama_model_loader: - kv   9:                         gemma3.block_count u32              = 34
llama_model_loader: - kv  10:                      gemma3.context_length u32              = 131072
llama_model_loader: - kv  11:                    gemma3.embedding_length u32              = 2560
llama_model_loader: - kv  12:                 gemma3.feed_forward_length u32              = 10240
llama_model_loader: - kv  13:                gemma3.attention.head_count u32              = 8
llama_model_loader: - kv  14:             gemma3.attention.head_count_kv u32              = 4
llama_model_loader: - kv  15:                   gemma3.rope.scaling.type str              = linear
llama_model_loader: - kv  16:                 gemma3.rope.scaling.factor f32              = 8.000000
llama_model_loader: - kv  17:                      gemma3.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  18:                  gemma3.rope.freq_base_swa f32              = 10000.000000
llama_model_loader: - kv  19:    gemma3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  20:                gemma3.attention.key_length u32              = 256
llama_model_loader: - kv  21:              gemma3.attention.value_length u32              = 256
llama_model_loader: - kv  22:            gemma3.attention.sliding_window u32              = 1024
llama_model_loader: - kv  23:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  24:                         tokenizer.ggml.pre str              = default
llama_model_loader: - kv  25:                      tokenizer.ggml.tokens arr[str,262208]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  26:                      tokenizer.ggml.scores arr[f32,262208]  = [-1000.000000, -1000.000000, -1000.00...
llama_model_loader: - kv  27:                  tokenizer.ggml.token_type arr[i32,262208]  = [3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  28:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  29:                tokenizer.ggml.eos_token_id u32              = 106
llama_model_loader: - kv  30:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  31:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  32:               tokenizer.ggml.mask_token_id u32              = 4
llama_model_loader: - kv  33:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  34:               tokenizer.ggml.add_sep_token bool             = false
llama_model_loader: - kv  35:                    tokenizer.chat_template str              = {{ bos_token }}{% if messages[0]['rol...
llama_model_loader: - kv  36:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - kv  37:               general.quantization_version u32              = 2
llama_model_loader: - kv  38:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  205 tensors
llama_model_loader: - type q4_K:  204 tensors
llama_model_loader: - type q6_K:   35 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 2.31 GiB (5.12 BPW)
llama_prepare_model_devices: using device CUDA0 (Tesla T4) (0000:00:04.0) - 10593 MiB free
init_tokenizer: initializing tokenizer for type 1
load: 6242 unused tokens
load: control token: 262144 '<image_soft_token>' is not marked as EOG
load: control token: 256000 '<end_of_image>' is not marked as EOG
load: control token: 255999 '<start_of_image>' is not marked as EOG
load: control token:    105 '<start_of_turn>' is not marked as EOG
load: control token:      2 '<bos>' is not marked as EOG
load: control-looking token:    212 '</s>' was not control-type; this is probably a bug in the model. its type will be overridden
load: control token:      0 '<pad>' is not marked as EOG
load: control token:      3 '<unk>' is not marked as EOG
load: control token:      4 '<mask>' is not marked as EOG
load: printing all EOG tokens:
load:   - 1 ('<eos>')
load:   - 106 ('<end_of_turn>')
load:   - 212 ('</s>')
load: special tokens cache size = 6415
load: token to piece cache size = 1.9446 MB
print_info: arch                  = gemma3
print_info: vocab_only            = 0
print_info: no_alloc              = 0
print_info: n_ctx_train           = 131072
print_info: n_embd_inp            = 2560
print_info: n_embd                = 2560
print_info: n_embd_out            = 2560
print_info: n_layer               = 34
print_info: n_layer_all           = 34
print_info: n_head                = 8
print_info: n_head_kv             = 4
print_info: n_rot                 = 256
print_info: n_swa                 = 1024
print_info: is_swa_any            = 1
print_info: n_embd_head_k         = 256
print_info: n_embd_head_v         = 256
print_info: n_gqa                 = 2
print_info: n_embd_k_gqa          = 1024
print_info: n_embd_v_gqa          = 1024
print_info: f_norm_eps            = 0.0e+00
print_info: f_norm_rms_eps        = 1.0e-06
print_info: f_clamp_kqv           = 0.0e+00
print_info: f_max_alibi_bias      = 0.0e+00
print_info: f_logit_scale         = 0.0e+00
print_info: f_attn_scale          = 6.2e-02
print_info: f_attn_value_scale    = 0.0000
print_info: n_ff                  = 10240
print_info: n_expert              = 0
print_info: n_expert_used         = 0
print_info: n_expert_groups       = 0
print_info: n_group_used          = 0
print_info: causal attn           = 1
print_info: pooling type          = -1
print_info: rope type             = 2
print_info: rope scaling          = linear
print_info: freq_base_train       = 1000000.0
print_info: freq_scale_train      = 0.125
print_info: freq_base_swa         = 10000.0
print_info: freq_scale_swa        = 1
print_info: n_embd_head_k_swa     = 256
print_info: n_embd_head_v_swa     = 256
print_info: n_rot_swa             = 256
print_info: n_ctx_orig_yarn       = 131072
print_info: rope_yarn_log_mul     = 0.0000
print_info: rope_finetuned        = unknown
print_info: model type            = 4B
print_info: model params          = 3.88 B
print_info: general.name          = Unsloth_Gguf_Giis7Gso
print_info: vocab type            = SPM
print_info: n_vocab               = 262208
print_info: n_merges              = 0
print_info: BOS token             = 2 '<bos>'
print_info: EOS token             = 106 '<end_of_turn>'
print_info: EOT token             = 106 '<end_of_turn>'
print_info: UNK token             = 3 '<unk>'
print_info: PAD token             = 0 '<pad>'
print_info: MASK token            = 4 '<mask>'
print_info: LF token              = 248 '<0x0A>'
print_info: EOG token             = 1 '<eos>'
print_info: EOG token             = 106 '<end_of_turn>'
print_info: EOG token             = 212 '</s>'
print_info: max token length      = 48
load_tensors: loading model tensors, this can take a while... (load_mode = mmap)
load_tensors: layer   0 assigned to device CUDA0, is_swa = 1
load_tensors: layer   1 assigned to device CUDA0, is_swa = 1
load_tensors: layer   2 assigned to device CUDA0, is_swa = 1
load_tensors: layer   3 assigned to device CUDA0, is_swa = 1
load_tensors: layer   4 assigned to device CUDA0, is_swa = 1
load_tensors: layer   5 assigned to device CUDA0, is_swa = 0
load_tensors: layer   6 assigned to device CUDA0, is_swa = 1
load_tensors: layer   7 assigned to device CUDA0, is_swa = 1
load_tensors: layer   8 assigned to device CUDA0, is_swa = 1
load_tensors: layer   9 assigned to device CUDA0, is_swa = 1
load_tensors: layer  10 assigned to device CUDA0, is_swa = 1
load_tensors: layer  11 assigned to device CUDA0, is_swa = 0
load_tensors: layer  12 assigned to device CUDA0, is_swa = 1
load_tensors: layer  13 assigned to device CUDA0, is_swa = 1
load_tensors: layer  14 assigned to device CUDA0, is_swa = 1
load_tensors: layer  15 assigned to device CUDA0, is_swa = 1
load_tensors: layer  16 assigned to device CUDA0, is_swa = 1
load_tensors: layer  17 assigned to device CUDA0, is_swa = 0
load_tensors: layer  18 assigned to device CUDA0, is_swa = 1
load_tensors: layer  19 assigned to device CUDA0, is_swa = 1
load_tensors: layer  20 assigned to device CUDA0, is_swa = 1
load_tensors: layer  21 assigned to device CUDA0, is_swa = 1
load_tensors: layer  22 assigned to device CUDA0, is_swa = 1
load_tensors: layer  23 assigned to device CUDA0, is_swa = 0
load_tensors: layer  24 assigned to device CUDA0, is_swa = 1
load_tensors: layer  25 assigned to device CUDA0, is_swa = 1
load_tensors: layer  26 assigned to device CUDA0, is_swa = 1
load_tensors: layer  27 assigned to device CUDA0, is_swa = 1
load_tensors: layer  28 assigned to device CUDA0, is_swa = 1
load_tensors: layer  29 assigned to device CUDA0, is_swa = 0
load_tensors: layer  30 assigned to device CUDA0, is_swa = 1
load_tensors: layer  31 assigned to device CUDA0, is_swa = 1
load_tensors: layer  32 assigned to device CUDA0, is_swa = 1
load_tensors: layer  33 assigned to device CUDA0, is_swa = 1
load_tensors: layer  34 assigned to device CUDA0, is_swa = 0
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor output_norm.weight
create_tensor: loading tensor output.weight
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor dense_2.weight
create_tensor: loading tensor dense_3.weight
create_tensor: loading tensor blk.0.attn_norm.weight
create_tensor: loading tensor blk.0.attn_qkv.weight
create_tensor: loading tensor blk.0.attn_q.weight
create_tensor: loading tensor blk.0.attn_k.weight
create_tensor: loading tensor blk.0.attn_v.weight
create_tensor: loading tensor blk.0.attn_q.bias
create_tensor: loading tensor blk.0.attn_k.bias
create_tensor: loading tensor blk.0.attn_v.bias
create_tensor: loading tensor blk.0.attn_output.weight
create_tensor: loading tensor blk.0.post_attention_norm.weight
create_tensor: loading tensor blk.0.attn_k_norm.weight
create_tensor: loading tensor blk.0.attn_q_norm.weight
create_tensor: loading tensor blk.0.ffn_norm.weight
create_tensor: loading tensor blk.0.ffn_gate.weight
create_tensor: loading tensor blk.0.ffn_up.weight
create_tensor: loading tensor blk.0.ffn_down.weight
create_tensor: loading tensor blk.0.post_ffw_norm.weight
create_tensor: loading tensor blk.1.attn_norm.weight
create_tensor: loading tensor blk.1.attn_qkv.weight
create_tensor: loading tensor blk.1.attn_q.weight
create_tensor: loading tensor blk.1.attn_k.weight
create_tensor: loading tensor blk.1.attn_v.weight
create_tensor: loading tensor blk.1.attn_q.bias
create_tensor: loading tensor blk.1.attn_k.bias
create_tensor: loading tensor blk.1.attn_v.bias
create_tensor: loading tensor blk.1.attn_output.weight
create_tensor: loading tensor blk.1.post_attention_norm.weight
create_tensor: loading tensor blk.1.attn_k_norm.weight
create_tensor: loading tensor blk.1.attn_q_norm.weight
create_tensor: loading tensor blk.1.ffn_norm.weight
create_tensor: loading tensor blk.1.ffn_gate.weight
create_tensor: loading tensor blk.1.ffn_up.weight
create_tensor: loading tensor blk.1.ffn_down.weight
create_tensor: loading tensor blk.1.post_ffw_norm.weight
create_tensor: loading tensor blk.2.attn_norm.weight
create_tensor: loading tensor blk.2.attn_qkv.weight
create_tensor: loading tensor blk.2.attn_q.weight
create_tensor: loading tensor blk.2.attn_k.weight
create_tensor: loading tensor blk.2.attn_v.weight
create_tensor: loading tensor blk.2.attn_q.bias
create_tensor: loading tensor blk.2.attn_k.bias
create_tensor: loading tensor blk.2.attn_v.bias
create_tensor: loading tensor blk.2.attn_output.weight
create_tensor: loading tensor blk.2.post_attention_norm.weight
create_tensor: loading tensor blk.2.attn_k_norm.weight
create_tensor: loading tensor blk.2.attn_q_norm.weight
create_tensor: loading tensor blk.2.ffn_norm.weight
create_tensor: loading tensor blk.2.ffn_gate.weight
create_tensor: loading tensor blk.2.ffn_up.weight
create_tensor: loading tensor blk.2.ffn_down.weight
create_tensor: loading tensor blk.2.post_ffw_norm.weight
create_tensor: loading tensor blk.3.attn_norm.weight
create_tensor: loading tensor blk.3.attn_qkv.weight
create_tensor: loading tensor blk.3.attn_q.weight
create_tensor: loading tensor blk.3.attn_k.weight
create_tensor: loading tensor blk.3.attn_v.weight
create_tensor: loading tensor blk.3.attn_q.bias
create_tensor: loading tensor blk.3.attn_k.bias
create_tensor: loading tensor blk.3.attn_v.bias
create_tensor: loading tensor blk.3.attn_output.weight
create_tensor: loading tensor blk.3.post_attention_norm.weight
create_tensor: loading tensor blk.3.attn_k_norm.weight
create_tensor: loading tensor blk.3.attn_q_norm.weight
create_tensor: loading tensor blk.3.ffn_norm.weight
create_tensor: loading tensor blk.3.ffn_gate.weight
create_tensor: loading tensor blk.3.ffn_up.weight
create_tensor: loading tensor blk.3.ffn_down.weight
create_tensor: loading tensor blk.3.post_ffw_norm.weight
create_tensor: loading tensor blk.4.attn_norm.weight
create_tensor: loading tensor blk.4.attn_qkv.weight
create_tensor: loading tensor blk.4.attn_q.weight
create_tensor: loading tensor blk.4.attn_k.weight
create_tensor: loading tensor blk.4.attn_v.weight
create_tensor: loading tensor blk.4.attn_q.bias
create_tensor: loading tensor blk.4.attn_k.bias
create_tensor: loading tensor blk.4.attn_v.bias
create_tensor: loading tensor blk.4.attn_output.weight
create_tensor: loading tensor blk.4.post_attention_norm.weight
create_tensor: loading tensor blk.4.attn_k_norm.weight
create_tensor: loading tensor blk.4.attn_q_norm.weight
create_tensor: loading tensor blk.4.ffn_norm.weight
create_tensor: loading tensor blk.4.ffn_gate.weight
create_tensor: loading tensor blk.4.ffn_up.weight
create_tensor: loading tensor blk.4.ffn_down.weight
create_tensor: loading tensor blk.4.post_ffw_norm.weight
create_tensor: loading tensor blk.5.attn_norm.weight
create_tensor: loading tensor blk.5.attn_qkv.weight
create_tensor: loading tensor blk.5.attn_q.weight
create_tensor: loading tensor blk.5.attn_k.weight
create_tensor: loading tensor blk.5.attn_v.weight
create_tensor: loading tensor blk.5.attn_q.bias
create_tensor: loading tensor blk.5.attn_k.bias
create_tensor: loading tensor blk.5.attn_v.bias
create_tensor: loading tensor blk.5.attn_output.weight
create_tensor: loading tensor blk.5.post_attention_norm.weight
create_tensor: loading tensor blk.5.attn_k_norm.weight
create_tensor: loading tensor blk.5.attn_q_norm.weight
create_tensor: loading tensor blk.5.ffn_norm.weight
create_tensor: loading tensor blk.5.ffn_gate.weight
create_tensor: loading tensor blk.5.ffn_up.weight
create_tensor: loading tensor blk.5.ffn_down.weight
create_tensor: loading tensor blk.5.post_ffw_norm.weight
create_tensor: loading tensor blk.6.attn_norm.weight
create_tensor: loading tensor blk.6.attn_qkv.weight
create_tensor: loading tensor blk.6.attn_q.weight
create_tensor: loading tensor blk.6.attn_k.weight
create_tensor: loading tensor blk.6.attn_v.weight
create_tensor: loading tensor blk.6.attn_q.bias
create_tensor: loading tensor blk.6.attn_k.bias
create_tensor: loading tensor blk.6.attn_v.bias
create_tensor: loading tensor blk.6.attn_output.weight
create_tensor: loading tensor blk.6.post_attention_norm.weight
create_tensor: loading tensor blk.6.attn_k_norm.weight
create_tensor: loading tensor blk.6.attn_q_norm.weight
create_tensor: loading tensor blk.6.ffn_norm.weight
create_tensor: loading tensor blk.6.ffn_gate.weight
create_tensor: loading tensor blk.6.ffn_up.weight
create_tensor: loading tensor blk.6.ffn_down.weight
create_tensor: loading tensor blk.6.post_ffw_norm.weight
create_tensor: loading tensor blk.7.attn_norm.weight
create_tensor: loading tensor blk.7.attn_qkv.weight
create_tensor: loading tensor blk.7.attn_q.weight
create_tensor: loading tensor blk.7.attn_k.weight
create_tensor: loading tensor blk.7.attn_v.weight
create_tensor: loading tensor blk.7.attn_q.bias
create_tensor: loading tensor blk.7.attn_k.bias
create_tensor: loading tensor blk.7.attn_v.bias
create_tensor: loading tensor blk.7.attn_output.weight
create_tensor: loading tensor blk.7.post_attention_norm.weight
create_tensor: loading tensor blk.7.attn_k_norm.weight
create_tensor: loading tensor blk.7.attn_q_norm.weight
create_tensor: loading tensor blk.7.ffn_norm.weight
create_tensor: loading tensor blk.7.ffn_gate.weight
create_tensor: loading tensor blk.7.ffn_up.weight
create_tensor: loading tensor blk.7.ffn_down.weight
create_tensor: loading tensor blk.7.post_ffw_norm.weight
create_tensor: loading tensor blk.8.attn_norm.weight
create_tensor: loading tensor blk.8.attn_qkv.weight
create_tensor: loading tensor blk.8.attn_q.weight
create_tensor: loading tensor blk.8.attn_k.weight
create_tensor: loading tensor blk.8.attn_v.weight
create_tensor: loading tensor blk.8.attn_q.bias
create_tensor: loading tensor blk.8.attn_k.bias
create_tensor: loading tensor blk.8.attn_v.bias
create_tensor: loading tensor blk.8.attn_output.weight
create_tensor: loading tensor blk.8.post_attention_norm.weight
create_tensor: loading tensor blk.8.attn_k_norm.weight
create_tensor: loading tensor blk.8.attn_q_norm.weight
create_tensor: loading tensor blk.8.ffn_norm.weight
create_tensor: loading tensor blk.8.ffn_gate.weight
create_tensor: loading tensor blk.8.ffn_up.weight
create_tensor: loading tensor blk.8.ffn_down.weight
create_tensor: loading tensor blk.8.post_ffw_norm.weight
create_tensor: loading tensor blk.9.attn_norm.weight
create_tensor: loading tensor blk.9.attn_qkv.weight
create_tensor: loading tensor blk.9.attn_q.weight
create_tensor: loading tensor blk.9.attn_k.weight
create_tensor: loading tensor blk.9.attn_v.weight
create_tensor: loading tensor blk.9.attn_q.bias
create_tensor: loading tensor blk.9.attn_k.bias
create_tensor: loading tensor blk.9.attn_v.bias
create_tensor: loading tensor blk.9.attn_output.weight
create_tensor: loading tensor blk.9.post_attention_norm.weight
create_tensor: loading tensor blk.9.attn_k_norm.weight
create_tensor: loading tensor blk.9.attn_q_norm.weight
create_tensor: loading tensor blk.9.ffn_norm.weight
create_tensor: loading tensor blk.9.ffn_gate.weight
create_tensor: loading tensor blk.9.ffn_up.weight
create_tensor: loading tensor blk.9.ffn_down.weight
create_tensor: loading tensor blk.9.post_ffw_norm.weight
create_tensor: loading tensor blk.10.attn_norm.weight
create_tensor: loading tensor blk.10.attn_qkv.weight
create_tensor: loading tensor blk.10.attn_q.weight
create_tensor: loading tensor blk.10.attn_k.weight
create_tensor: loading tensor blk.10.attn_v.weight
create_tensor: loading tensor blk.10.attn_q.bias

✅ Modelo cargado con éxito en VRAM

Ahora inferimos el modelo de Gemma 3 para obtener los comentarios en base a los 7 ejemplos de prompt del conjunto de test. Almecelamos las respuestas en el campo 'answers' del diccionario requerido por Ragas.

In [ ]:
# 3. Generar las respuestas con tu modelo Fine-Tuned (usando llama-cpp-python)
answers = []
print("Generando respuestas con Gemma 3 Fine-Tuned para el test...")

n = 0

for system_instruction, user_data in zip(df_eval['instructions'], df_eval['contexts']):
    # Formato de mensajes para el motor de chat
    n += 1

    print(n)

    messages = [
        {"role": "system", "content": system_instruction},
        {"role": "user", "content": user_data}
    ]

    # Inferencia directa usando la API de chat de llama-cpp-python
    response = model.create_chat_completion(
        messages=messages,
        max_tokens=2000,
        temperature=0.1
    )

    # Extraer el texto generado por la respuesta del asistente
    respuesta = response["choices"][0]["message"]["content"]
    answers.append(respuesta)

print("✅ Todas las respuestas generadas con éxito.")

# 4. Estructurar el diccionario 'data' para Ragas
data = {
    "question": df_eval['question'].tolist(),
    "contexts": [[item] for item in df_eval['contexts'].tolist()], # Solo los datos brutos como fuente de verdad
    "answer": answers,                                             # Salidas generadas por Gemma 3
    "ground_truth": df_eval['ground_truth'].tolist()               # Comentario humano ideal
}

# 5. Convertir a Dataset de Hugging Face
eval_dataset = Dataset.from_dict(data)
print("✅ 'data' y 'eval_dataset' construidos correctamente con las 4 columnas requeridas.")

Generando respuestas con Gemma 3 Fine-Tuned para el test...
1

CUDA Graph id 87 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
CUDA Graph id 87 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 90 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
CUDA Graph id 90 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 93 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
CUDA Graph id 93 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 96 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused
CUDA Graph id 96 reused

2

CUDA Graph id 132 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
CUDA Graph id 132 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 135 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
CUDA Graph id 135 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 138 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
CUDA Graph id 138 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 141 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused
CUDA Graph id 141 reused

3

CUDA Graph id 174 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
CUDA Graph id 174 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 177 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
CUDA Graph id 177 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 180 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
CUDA Graph id 180 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 183 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused
CUDA Graph id 183 reused

4

CUDA Graph id 216 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
CUDA Graph id 216 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 219 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
CUDA Graph id 219 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 222 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
CUDA Graph id 222 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 225 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused
CUDA Graph id 225 reused

5

CUDA Graph id 264 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
CUDA Graph id 264 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 267 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
CUDA Graph id 267 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 270 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
CUDA Graph id 270 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 273 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused
CUDA Graph id 273 reused

6

CUDA Graph id 306 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
CUDA Graph id 306 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 309 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
CUDA Graph id 309 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 312 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
CUDA Graph id 312 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 315 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused
CUDA Graph id 315 reused

7

CUDA Graph id 345 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
CUDA Graph id 345 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 348 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
CUDA Graph id 348 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 351 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
CUDA Graph id 351 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup reset
CUDA Graph id 354 reused
ggml_backend_cuda_graph_compute: CUDA graph warmup complete
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused
CUDA Graph id 354 reused

✅ Todas las respuestas generadas con éxito.
✅ 'data' y 'eval_dataset' construidos correctamente con las 4 columnas requeridas.

Echamos un vistazo a las respuestas del modelo. Se ve que en el último caso el modelo repite de forma sistemática una frase, lo cual no es precisamente bueno.

In [ ]:
answers

['## ANÁLISIS DE MERCADOS - 20 DE AGOSTO DE 2026\n\n**Rendimiento de Renta Variable (PECENTOS 20/08/2026):**\n\n- S&P500: +0.21%\n- S&P Equal Weight (SPW): +1.02%\n- 7 Magníficas (BM7T): +1.23%\n- EuroStoxx50: -0.37%\n- Stoxx600: -0.11%\n- Ibex35: -0.44%\n\n*Análisis:* El S&P500 y las 7 Magníficas se han apreciado ligeramente, impulsados en parte por datos de norteamericano y en menor medida europeo. El S&P Equal Weight ha superado al S&P500 en más de un punto, y las 7 Magníficas han tenido el mejor rendimiento de todos. El EuroStoxx50 y el Stoxx600 han tenido resultados negativos, principalmente por el sector bancario en Europa. El Ibex35 ha cerrado en rojo, con una diferencia de más de un punto por centos entre sus máximos y mínimos de la sesión.\n\n**Rendimiento de Materias Primas:**\n\n- Petróleo Brent: $91.9/barril\n- Petróleo WTI: $86.0/barril\n\n*Análisis:* Los precios del petróleo han subido ligeramente, por encima de los $92 y $86, respectivamente.\n\n**Rendimiento de Renta Fija (Yields bonos 10 años - 20/08/2026):**\n\n- Bono EEUU: 4.64%\n- Bono Alemania: 3.26%\n- Bono España: 3.70%\n\n*Análisis:* Los bonos norteamericanos se han negociado a 4.64%, los bonos alemanes a 3.26% y los bonos españoles a 3.70%.\n\n**Expectativas de Tipos de la Fed, BCE y BOE (20/08/2026):**\n\n- FED: A diciembre se descuenta por parte de la Fed una subida de 21,5 puntos básicos, y a marzo 1977 una subida de 31 puntos básicos\n- BCE: A diciembre se descuenta por parte del BCE una subida de 41,9 puntos básicos, y a marzo 1977 una subida de 53,5 puntos básicos\n- BOE: A diciembre se descuenta por parte del BOE una subida de 26,6 puntos básicos, y a marzo 1977 una subida de 49,5 puntos básicos\n\n**Renta Variable en detalle:**\n\n- El S&P500 ha subido en su día más alto en más de 1,5%, por encima de ATH de 4.800 puntos, gracias en parte a datos de norteamericano, que han tenido un impacto positivo en el sector de salud, de materiales y de consumo discrecional.\n- El S&P Equal Weight ha tenido el mejor día de todos, por encima de 1,02%, por encima de su ATH de 1,30%\n- Las 7 Magníficas han tenido el mejor día de todos, por encima de 1,23%, por encima de su ATH de 1,50%\n- El S&P Equal Weight ha superado al S&P500 en más de un punto, y las 7 Magníficas han tenido el mejor rendimiento de todos. El EuroStoxx50 y el Stoxx600 han tenido resultados negativos, principalmente por el sector bancario en Europa. El Ibex35 ha cerrado en rojo, con una diferencia de más de un punto por centos entre sus máximos y mínimos de la sesión.\n\n**Rendimiento corporativo en EEUU y Europa:**\n\n- Novonesis ha mejorado sus expectativas de crecimiento orgánico en el 2026, por encima de lo que se esperaba, por 1,5 puntos, y ahora se espera que crezca entre el 7% y el 8% en lugar de entre el 5% y el 7%\n- GN Store Nord ha mejorado sus expectativas de margen en el 2026, por encima de lo que se esperaba, por 1,2 puntos, y ahora se espera que tenga un margen de 9,1% en lugar de 8,1%\n- Los datos de resultados empresariales en EEUU y Europa han tenido un impacto positivo en el S&P500, que ha subido en su día más alto en más de 1,5%, por encima de ATH de 4.800 puntos, gracias en parte a datos de norteamericano, que han tenido un impacto positivo en el sector de salud, de materiales y de consumo discrecional.\n\n**Datos macro a conocerse:**\n\n- Los datos macro a conocerse hoy en EEUU, UK y la Eurozona son especialmente importantes, y se han tenido en cuenta en el análisis de renta variable y renta fija.\n\n**RÉSUMEN DE EXPECTATIVAS DE TIPOS DE LA FED, BCE Y BOE (20/08/2026):**\n\n- La Fed, el BCE y el BOE tienen por ahora la intención de subir los tipos de interés en los próximos meses, por 21,5, 41,9 y 26,6 puntos básicos, respectivamente.\n\n**DISCLAIMER:** Este comentario de mercados se basa en datos reales y las noticias proporcionadas. No es un consejo de inversión. Los mercados pueden ser volátiles y los datos de hoy pueden tener un impacto diferente en el mercado de hoy y en los días siguientes.\n\nFin de comentario.\n20 de agosto de 2026.\nAnalista Senior.\n',
 '## Análise de Mercados - 21 de agosto de 2026\n\n**Rendimentos de Materias Primas:**\n\nOs contratos futuros de petróleo bruto, tanto Brent como WTI, estão a abrir a sessão hoje a 93,5/barril e 86,4/barril, respetivamente, com subidas de 0,38% e 0,56% nos termos de variação diária. Os preços estão a mostrar-se, por conseguinte, mais estáveis do que ontem, e a subida de WTI é a mais significativa da semana. Os preços de petróleo estão a ser impulsionados, em parte, por expectativas de aumento da procura de petróleo a causa da temporada de verões nos Estados Unidos e na Europa, bem como por temores de cortes de produção pela OPEP+ a fim de sustentar os preços.\n\n**Rendimentos de Ativos Fixos:**\n\nOs rendimentos dos títulos de vencimento de 10 anos estão a abrir a sessão hoje a 4,70% para os dos EUA, 3,26% para os alemães e 3,70% para os espanhóis. Os rendimentos dos títulos norte-americanos têm-se mantido relativamente estáis, enquanto os dos países de norte da Europa têm-se mantido mais voláteis, com os dos países de norte da Europa a subir 5,4 pontos básicos, e os dos países de sul a subir 1,6 pontos básicos.\n\n**Risco de Reserva Federal:**\n\nA Fed está a ser vista a dezembro a subir os tipos 22,9 pontos básicos, e a março 2027 a subir 33,1 pontos básicos. A Fed tem-se mostrado, por conseguinte, mais inclinada a continuar a política monetária restritiva do que o BCE.\n\n**Rendimentos de Ativos Fixos:**\n\nO BCE está a ser visto a dezembro a subir os tipos 45,6 pontos básicos, e a março 2027 a subir 55 pontos básicos. O BCE tem-se mostrado, por conseguinte, mais inclinada a continuar a política monetária restritiva do que a Fed.\n\n**Rendimentos de Ativos Fixos:**\n\nO BOE está a ser visto a dezembro a subir os tipos 27,1 pontos básicos, e a março 2027 a subir 45,9 pontos básicos. O BOE tem-se mostrado, por conseguinte, mais inclinada a continuar a política monetária restritiva do que a Fed ou o BCE.\n\n**Rendimentos de Ativos Fixos:**\n\nA Fed está a ser vista a dezembro a subir os tipos 22,9 pontos básicos, e a março 2027 a subir 33,1 pontos básicos. O BCE está a ser visto a dezembro a subir os tipos 45,6 pontos básicos, e a março 2027 a subir 55 pontos básicos. O BOE está a ser visto a dezembro a subir os tipos 27,1 puntos básicos, y a marzo 2027 a subir 45,9 puntos básicos.\n\n**Rendimiento de Renta Variable:**\n\nO S&P 500 está a abrir a sesión hoy a -0,87%, y el S&P Equal Weight a -0,81%. Los mercados norteamericanos están, por tanto, en terreno negativo, y se han visto especialmente afectados los sectores de materiales y de servicios, que han perdido el 1,5% y el 1,6% respectivamente. El S&P 7 Magníficas, por su parte, está a abrir a -1,08%.\n\nEl Stoxx 600 está a abrir a -0,35%, y el Stoxx 600 está, por tanto, en terreno negativo, y se han visto especialmente afectados los sectores de retail y de servicios, que han perdido el 1,02% y el 1,16% respectivamente.\n\nEl Ibex 35 está a abrir a -0,18%, y el Ibex 35 está, por tanto, en terreno negativo, y se han visto especialmente afectados los sectores de materiales y de servicios, que han perdido el 1,5% y el 1,6% respectivamente.\n\n**Rendimiento de Renta Fija:**\n\nLos tipos de los bonos norteamericanos están a abrir a 4,70%, los tipos de los bonos alemanes a 3,26% y los tipos de los bonos españoles a 3,70%.\n\n**Rendimiento de Renta Fija:**\n\nLos tipos de los bonos norteamericanos están a abrir a 4,70%, los tipos de los bonos alemanes a 3,26% y los tipos de los bonos españoles a 3,70%.\n\n**Rendimiento de Renta Fija:**\n\nLos tipos de los bonos norteamericanos están a abrir a 4,70%, los tipos de los bonos alemanes a 3,26% y los tipos de los bonos españoles a 3,70%.\n\n**Rendimiento de Renta Fija:**\n\nLos tipos de los bonos norteamericanos están a abrir a 4,70%, los tipos de los bonos alemanes a 3,26% y los tipos de los bonos españoles a 3,70',
 '## COMENTO DE MERCADOS - 24 de agosto de 2026\n\n**Rendimiento de Renta Variable (S, % día anterior):**\n\nRenta variable se ha tenido una sesión en general positiva, con los S&P500, S7T y BM7T subiendo en torno al 0,4% y 0,6% respectivamente. El S&P Equal Weight (SPW) ha tenido un comportamiento más discreto, con un aumento de 0,1%. El EuroStoxx50 ha cerrado en positivo, con un aumento de 0,6%. El Ibex35 ha tenido un comportamiento mejor, con un aumento de 0,76%. El Nikkei ha cerrado en negativo, con una pérdida de 0,57%.\n\nEn términos de sector, en el S&P500, los sectores de Materiales han liderado la subida, con un aumento de 2,2%, seguido de por los de Servicios Financeros, que han subido 1,3% y de Salud, que han subido 1,1%. El peor sector de S&P500 ha sido el de Utilities, que ha perdido 2,31%. En el Stoxx60, el sector de Recursos Básicos ha liderado la subida, con un aumento de 2,49%, seguido de por el de Salud, que ha subido 1,6% y de Servicios Financeros, que han subido 1,4%. El peor sector de Stoxx60 ha sido el de Petróleo, que ha perdido 0,68%.\n\nEn cuanto a ratios PE y crecimiento de EPS, el S&P500 tiene un PE de 21,3x y un crecimiento de EPS estimado en +34,5% en 2026. El Stoxx60 tiene un PE de 15,9x y un crecimiento de EPS estimado en +16,3% en 2026.\n\nRachas de 10 semanas: El S&P Financials ha subido en 9 de las últimas 10 semanas, y el S&P Telecoms ha subido en 8 de las últimas 10 semanas. El S&P Financials ha bajado en 9 de las últimas 10 semanas, y el S&P Telecoms ha bajado en 8 de las últimas 10 semanas. El S&P Telecoms acumula 6 semanas consecutivas al alza, y el S&P Financials acumula 4 semanas consecutivas al alza.\n\n**Renta Fija, Tipos de Interés y Reserva Federal:**\n\nLos bonos de 10 años han cerrado la sesión en el 4,71% (USA), 3,26% (Alemania) y 3,71% (España). El diferencial entre el bono de EEUU y el bono de Alemania se ha reducido en 15 puntos básicos en la última semana, y en 10 en la semana anterior. El bono de España ha subido 15 puntos básicos en la última semana, y en 12 en la semana anterior.\n\nLa Fed se mantiene en la línea de subir los tipos en 25 puntos básicos en diciembre y en marzo de 2027, por lo que se descuenta en este momento 2,6% en tipos de 10 años. El BCE se descuenta en este momento 3,6% en tipos de 10 años, y el BOE se descuenta en este momento 3,0% en tipos de 10 años.\n\n**Rendimiento Corporativo en EEUU y Europa:**\n\nRendimiento corporativo en EEUU: Las empresas de S&P500 han presentado resultados en general mejores de lo esperado, con un aumento de sus beneficios en el último trimestre. Los datos de personal en EEUU han aumentado en 150.000 en el pasado trimestre, por encima de las expectativas, y la tasa de desempleo se ha situado en 4,3%.\n\nRendimiento corporativo en Europa: Las empresas de Stoxx600 han presentado resultados en general mejores de lo esperado, con un aumento de sus beneficios en el último trimestre. Los datos de personal en la Eurozona han aumentado en 50.000 en el pasado trimestre, por encima de las expectativas, y la tasa de desempleo se ha situado en 6,7%.\n\n**Datos Macro a conocerse:**\n\nLos datos macro a conocerse en EEUU, UK y la Eurozona son:\n\n- EEUU: La inflación se ha situado en 2,1% en julio, por encima de las expectativas, y la tasa de desempleo se ha situado en 4,3%.\n- UK: La inflación se ha situado en 3,5% en julio, por encima de las expectativas, y la tasa de desempleo se ha situado en 4,3%.\n- Eurozona: La inflación se ha situado en 2,3% en julio, por encima de las expectativas, y la tasa de desempleo se ha situado en 6,7%.\n\n**Rieume de expectativas de tipos de la Fed, BCE y BOE:**\n\n- La Fed se descuenta en este momento 2,6% en tipos de 10 años, y en marzo de 2027 se descuentan 3,6% en tipos de 10 años.\n- El BCE se descuenta en este momento 3,6% en tipos de 10 años, y en marzo de R4 2027 se descuenta 5,8% en tipos de 10 años.\n- El BOE se descuenta en este momento 3,0% en tipos de 10 años, y en marzo de R4 2027 se descuenta 4,3% en tipos de 10 años.\n\n**Renta Variable en resumen:**\n\nRenta variable se ha tenido una sesión en general positiva, con los S&P500, S7T y BM7T subiendo en torno al 0,4% y 0,6% respectivamente. El S&P Equal Weight (SPW) ha tenido un comportamiento más discreto, con un aumento de 0,1%. El EuroStoxx50 ha cerrado en positivo, con un aumento de 0,6%. El Ibex35 ha tenido un comportamiento mejor, con un aumento de 0,76%. El Nikkei ha cerrado en negativo, con una pérdida de 0,57%.\n\nEn cuanto a ratios PE y crecimiento de EPS, el S&P500 tiene un PE de 21,3x y un crecimiento de EPS estimado en +34,5% en 2026. El Stoxx60 tiene un PE de 15,9x y un crecimiento de EPS estimado en +16,3',
 '## Análise de Mercados - 26 de Agosto de 2026\n\n**Rendimentos de Materias Primas:**\n\nOs mercados de petróleo se abrem com ganhos modestos, com o Brent a negociar acima de $92,00/barril e o WTI a $85,00/barril. O Brent subiu 0,7% e o WTI 0,5% na abertura. Apesar de estes números, ambos os crudes estão a mais de 1,5% abaixo das máximas de 2026, que se situam agora a $96,70 e $107,70, respetivamente. A tensão geopolítica no Oriente Médio, especialmente a situação em torno de Irão, continua a ser o principal fator de incerteza para o mercado de petróleo, e a falta de progresso nas negociações entre as partes em conflito tem contribuído para a volatilidade.\n\n**Rendimentos de Ativos Fixos (Renta Fixa):**\n\nOs rendimentos dos títulos de 10 anos estão a abrir hoje a 4,71% (EUA), 3,25% (Alemanha) e 3,71% (Espanha). Os números norte-americanos são os mais altos, e a diferença de 1,46% entre os dos países de norte e sul da Europa, é a maior que se tem visto desde o início de ano. Os mercados de norte-americano têm a maior parte de responsabilidade, porque a Fed está a subir os tipos a un ritmo muito mais rápido que BCE e BOE.\n\nA Fed está a antecipar subidas de 27,8 pontos básicos em dezembro de 2026 e 39,7 pontos básicos em março de 2027. O BCE, por sua vez, está a antecipar subidas de 42,9 pontos básicos em dezembro de 2026 e 55,5 pontos básicos em março de 027. O BOE, por último, está a antecipar subidas de 32,7 pontos básicos em dezembro de 2026 e 49,3 pontos básicos em março de 2027.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nApesar das expectativas de subidas de tipos, os mercados de norte-americano, especialmente os de 10 anos, estão a subir, o que indica que os mercados temem que a Fed tenha que subir más de tipos de lo que se está a anteponer.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nA Fed está a manter a política monetária restritiva, com a expectativa de subir os tipos en 1,50 puntos básicos en los próximos 12 meses. El BCE, por su parte, está a ir a un ritmo más moderado, con una subida de 0,75 puntos básicos en los próximos 12 meses. El BOE, por último, está a ir a un ritmo aún más moderado, con una subida de 0,5 puntos básicos en los próximos 12 meses.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nA Fed está a mantener la política monetaria restrictiva, con la expectativa de subir los tipos en 1,50 puntos básicos en los próximos 12 meses. El BCE, por su parte, está a ir a un ritmo más moderado, con una subida de 0,75 puntos básicos en los próximos 12 meses. El BOE, por último, está a ir a un ritmo aún más moderado, con una subida de 0,5 puntos básicos en los próximos 12 meses.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nA Fed está a mantener la política monetaria restrictiva, con la expectativa de subir los tipos en 1,50 puntos básicos en los próximos 12 meses. El BCE, por su parte, está a ir a un ritmo más moderado, con una subida de 0,75 puntos básicos en los próximos 12 meses. El BOE, por último, está a ir a un ritmo aún más moderado, con una subida de 0,5 puntos básicos en los próximos 12 meses.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nA Fed está a mantener la política monetaria restrictiva, con la expectativa de subir los tipos en 1,50 puntos básicos en los próximos 12 meses. El BCE, por su parte, está a ir a un ritmo más moderado, con una subida de 0,75 puntos básicos en los próximos 12 meses. El BOE, por último, está a ir a un ritmo aún más moderado, con una subida de 0,5 puntos básicos en los próximos 12 meses.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nA Fed está a mantener la política monetaria restrictiva, con la expectativa de subir los tipos en 1,50 puntos básicos en los próximos 12 meses. El BCE, por su parte, está a ir a un ritmo más moderado, con una subida de 0,75 puntos básicos en los próximos 12 meses. El BOE, por último, está a ir a un ritmo aún más moderado, con una subida de 0,5 puntos básicos en los próximos 12 meses.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nA Fed está a mantener la política monetaria restrictiva, con la expectativa de subir los tipos en 1,50 puntos básicos en los próximos 12 meses. El BCE, por su parte, está a ir a un ritmo más moderado, con una subida de 0,75 puntos básicos en los próximos 12 meses. El BOE, por último, está a ir a un ritmo aún más moderado, con una subida de 0,5 puntos básicos en los próximos 12 meses.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nA Fed está a mantener la política monetaria restrictiva, con la expectativa de subir los tipos en 1,50 puntos básicos en los próximos 12 meses. El BCE, por su parte, está a ir a un ritmo más moderado, con una subida de 0,75 puntos básicos en los próximos 12 meses. El BOE, por último, está a ir a un ritmo aún más moderado, con una subida de 0,5 puntos básicos en los próximos 12 meses.\n\n**Rendimentos de Ativos Fixos (Renta Fija):**\n\nA Fed está a mantener la política monetaria restrictiva, con la expectativa de subir los tipos en 1,50 puntos básicos en los próximos 12 meses. El BCE, por su parte, está a ir a un ritmo más moderado, con una subida de 0,75 puntos básicos en los próximos 12 meses. El BOE, por último, está a ir a un ritmo aún más moderado, con una subida de 0,5 puntos básicos en los próximos 12 meses.\n\n**R',

Definimos las métricas de Ragas a determinar.

In [ ]:
# Definir métricas principales de Ragas
metrics = [
    faithfulness,         # ¿La respuesta generada se basa solo en el contexto?
    context_precision,    # ¿El contexto recuperado es relevante para la pregunta?
    answer_relevancy,
    context_recall,       # ¿El contexto contiene toda la información de la ground_truth?
]

Tuvimos varios errores 401, con lo que nos aseguramos inicialmente que podemos contactar con DeepSeek.

In [ ]:
from openai import OpenAI

client = OpenAI(
    api_key=DEEPSEEK_API_KEY,
    base_url="https://api.deepseek.com"   # ← correcto para DeepSeek directo
)

response = client.chat.completions.create(
    model="deepseek-chat",                 # ← nombre del modelo en DeepSeek directo
    messages=[{"role": "user", "content": "Di solo: OK"}],
    max_tokens=10
)
print(response.choices[0].message.content)

¡Hola! 😄

¿Listo

Este es el código de la implementación de Ragas, que define el judge, baja los embeddings de un modelo simple, y calcula las métricas, guardando los resultados y los datos de origen en un dataframe de Pandas.

In [ ]:
from openai import OpenAI
from ragas.llms import llm_factory
from langchain_community.embeddings import HuggingFaceEmbeddings
from ragas.embeddings import LangchainEmbeddingsWrapper

openai_client = OpenAI(
    api_key=DEEPSEEK_API_KEY,
    base_url="https://api.deepseek.com"
)

ragas_judge = llm_factory(
    model="deepseek-chat",
    client=openai_client,
    max_tokens=4096
)

lc_embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)
ragas_embeddings = LangchainEmbeddingsWrapper(lc_embeddings)

for metric in metrics:
    metric.llm = ragas_judge
    if hasattr(metric, "embeddings"):
        metric.embeddings = ragas_embeddings

print("Ejecutando evaluación con DeepSeek Chat...")
result = evaluate(
    dataset=eval_dataset,
    metrics=metrics,
    llm=ragas_judge,
    embeddings=ragas_embeddings
)

print("\n--- RESULTADOS GLOBALES ---")
print(result)

# Convertir a Pandas DataFrame para análisis detallado fila por fila
df_results = result.to_pandas()
df_results.head(7)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/tmp/ipykernel_48715/3301101576.py:20: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_embeddings = LangchainEmbeddingsWrapper(lc_embeddings)

Ejecutando evaluación con DeepSeek Chat...

Evaluating:   0%|          | 0/28 [00:00<?, ?it/s]

WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
ERROR:ragas.executor:Exception raised in Job[20]: IncompleteOutputException(The output is incomplete due to a max_tokens length limit.)
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
ERROR:ragas.executor:Exception raised in Job[24]: IncompleteOutputException(The output is incomplete due to a max_tokens length limit.)
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

--- RESULTADOS GLOBALES ---
{'faithfulness': 0.4715, 'context_precision': 1.0000, 'answer_relevancy': 0.4055, 'context_recall': 0.9311}

,user_input,retrieved_contexts,response,reference,faithfulness,context_precision,answer_relevancy,context_recall
0,Eres un analista financiero senior. Debes reda...,[## DATOS NUMÉRICOS DE MERCADO (USA ESTOS VALO...,## ANÁLISIS DE MERCADOS - 20 DE AGOSTO DE 2026...,**La renta variable estadounidense** cerró aye...,0.581395,1.0,0.430233,0.967742
1,Eres un analista financiero senior. Debes reda...,[## DATOS NUMÉRICOS DE MERCADO (USA ESTOS VALO...,## Análise de Mercados - 21 de agosto de 2026\...,**Wall Street** encadena su quinta sesión cons...,0.227273,1.0,0.476711,1.000000
2,Eres un analista financiero senior. Debes reda...,[## DATOS NUMÉRICOS DE MERCADO (USA ESTOS VALO...,## COMENTO DE MERCADOS - 24 de agosto de 2026\...,**La renta variable europea afronta una sesión...,0.800000,1.0,0.424005,0.923077
3,Eres un analista financiero senior. Debes reda...,[## DATOS NUMÉRICOS DE MERCADO (USA ESTOS VALO...,## Análise de Mercados - 26 de Agosto de 2026\...,**Las bolsas europeas apuntan a una apertura l...,0.387097,1.0,0.485037,0.960000
4,Eres un analista financiero senior. Debes reda...,[## DATOS NUMÉRICOS DE MERCADO (USA ESTOS VALO...,## COMENTO DE MERCADOS - 26 de agosto de 2026\...,**La renta variable estadounidense cerró ayer ...,0.361702,1.0,0.545854,0.703704
5,Eres un analista financiero senior. Debes reda...,[## DATOS NUMÉRICOS DE MERCADO (USA ESTOS VALO...,## Comentario de Mercados - 27 de Septiembre d...,**Nvidia** ha vuelto a ejercer como catalizado...,NaN,1.0,0.236598,0.962963
6,Eres un analista financiero senior. Debes reda...,[## DATOS NUMÉRICOS DE MERCADO (USA ESTOS VALO...,## ANÁLISIS DE MERCADOS - 28 DE AGOSTO DE 2026...,**La renta variable norteamericana cerró ayer ...,NaN,1.0,0.240248,1.000000

Guardamos los resultados completos en nuestro Drive, así como una versión muy abreviada, solo con los datos de las métricas.

In [ ]:
# Guardar en CSV para anexarlo a la memoria de tu proyecto
df_results.to_csv("/content/drive/MyDrive/Ollama_app_comentario/evaluacion_ragas_deepseek.csv", index=False)
print("Evaluación guardada en Google Drive correctamente.")

Evaluación guardada en Google Drive correctamente.

In [ ]:
df_results.columns

Index(['user_input', 'retrieved_contexts', 'response', 'reference',
       'faithfulness', 'context_precision', 'answer_relevancy',
       'context_recall'],
      dtype='object')

In [ ]:
df_solo_metricas = df_results.drop(columns=['user_input', 'retrieved_contexts', 'response', 'reference'])

In [ ]:
df_solo_metricas.head()

   faithfulness  context_precision  answer_relevancy  context_recall
0      0.581395                1.0          0.430233        0.967742
1      0.227273                1.0          0.476711        1.000000
2      0.800000                1.0          0.424005        0.923077
3      0.387097                1.0          0.485037        0.960000
4      0.361702                1.0          0.545854        0.703704

In [ ]:
df_solo_metricas.to_csv("/content/drive/MyDrive/Ollama_app_comentario/evaluacion_ragas_deepseek_metricas.csv", index=False)
print("Evaluación guardada en Google Drive correctamente.")

Evaluación guardada en Google Drive correctamente.